name: Silent Hill 2 0.10 VW047-U1
sha1: 888eff71606ff4c1c610e30111b3ca5da647edcc
options:
  basename: SLUS_202.28
  base_path: .
  target_path: rom/SLUS_202.28
  elf_path: SLUS_202.28
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  ld_script_path: linkers/SLUS_202.28.ld
  undefined_funcs_auto_path: linkers/sh2_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/sh2_undefined_syms_auto.main.txt
  asm_nonmatching_label_macro: ""
  symbol_addrs_path: symbol_addrs.txt
  migrate_rodata_to_functions: True
  pair_rodata_to_text: True
segments:
  - [0x0]
  - name: engine
    type: code
    start: 0x700
    vram: 0x00100000
    bss_size: 0x1b3a080
    subsegments:
      - [0x000700, asm, crt0]
      - [0x0007c0, asm, Chacter/anime]
      - [0x001710, asm, Chacter/fi_libvu0_inline]
      - [0x003580, asm, Chacter/bg_obj_stay]
      - [0x003670, asm, Chacter/item_screen_obj]
      - [0x003d10, asm, Chacter/m3_angela]
      - [0x004290, asm, Chacter/m3_anime_subfunc]
      - [0x004620, asm, Chacter/m3_bgobj]
      - [0x004bd0, asm, Chacter/m3_djames]
      - [0x005250, asm, Chacter/m3_dmaria]
      - [0x005550, asm, Chacter/m3_eddie]
      - [0x005830, asm, Chacter/m3_ike]
      - [0x005d20, asm, Chacter/m3_laura]
      - [0x005fc0, asm, Chacter/m3_mkn]
      - [0x006560, asm, Chacter/m3_pap]
      - [0x006aa0, asm, Chacter/m3_play]
      - [0x011a70, asm, Chacter/m3_play_2d]
      - [0x016180, asm, Chacter/m3_play_3d]
      - [0x01d080, asm, Chacter/m3_red]
      - [0x01d610, c,   Chacter/m3_sc]
      - [0x01ffc0, asm, Chacter/m3_scu]
      - [0x0206d0, asm, Chacter/m3_wep]
      - [0x020ca0, asm, Chacter/sh_character_battle]
      - [0x024170, asm, Chacter/sh_character_status]
      - [0x0245b0, asm, SH2_common/sh_vu0]
      - [0x0255f0, asm, Chacter/skelton]
      - [0x025880, asm, Chacter_Draw/vifot/sh_kt_pkbuf]
      - [0x0258e0, asm, Chacter_Draw/vifot/sh_kt_vif0]
      - [0x025a20, asm, Chacter_Draw/vifot/sh_kt_vif0pkbuf]
      - [0x025b00, asm, Chacter_Draw/vifot/sh_kt_vif1]
      - [0x025b50, asm, Chacter_Draw/vifot/sh_kt_vif1ot2]
      - [0x025f10, asm, Chacter_Draw/vifot/sh_kt_vif1pkbuf]
      - [0x025fc0, asm, Chacter_Draw/clani]
      - [0x026760, asm, Chacter_Draw/light_n]
      - [0x027f80, asm, Chacter_Draw/model3_cluster_n]
      - [0x028730, asm, Chacter_Draw/model3_equip_n]
      - [0x0287e0, asm, Chacter_Draw/model3_n]
      - [0x029000, asm, Chacter_Draw/model3_sub_n]
      - [0x0295f0, c,   Chacter_Draw/model3_vu0_n]
      - [0x02c4e0, c,   Chacter_Draw/model3_vu1_n]
      - [0x02e4c0, asm, Chacter_Draw/model_common]
      - [0x02e540, asm, Chacter_Draw/model_n]
      - [0x02e580, asm, Chacter_Draw/sh2gfw_CharacterOT]
      - [0x02e8d0, asm, Chacter_Draw/sh2gfw_Draw_Character]
      - [0x02f7a0, asm, Chacter_Draw/sh2gfw_md_spclmapping]
      - [0x02fad0, asm, Chacter_Draw/sh2gfw_model_light]
      - [0x031c10, asm, Chacter_Draw/sh_kt_vu0]
      - [0x031c90, asm, Collision/cl_calc]
      - [0x031ce0, asm, Collision/cl_calc2]
      - [0x0327b0, asm, Collision/cl_main]
      - [0x03ae80, asm, Collision/kari_atari_allinit]
      - [0x03aed0, asm, DBG/sh2gfw_SyncDBG]
      - [0x03aff0, asm, Effect/ef_broken_glass]
      - [0x03c590, asm, Effect/ef_common]
      - [0x03e5f0, asm, Effect/ef_malloc]
      - [0x03e700, asm, Effect/ef_packet]
      - [0x03e840, asm, Effect/ef_stage]
      - [0x040110, asm, Enemy/en_bos]
      - [0x041ab0, asm, Enemy/en_common]
      - [0x047f50, asm, Enemy/en_draw]
      - [0x049bc0, asm, Enemy/en_edb]
      - [0x04e720, asm, Enemy/en_effect]
      - [0x051250, asm, Enemy/en_ike]
      - [0x053b10, asm, Enemy/en_mkn]
      - [0x057eb0, asm, Enemy/en_nse]
      - [0x05a760, asm, Enemy/en_pap]
      - [0x05db10, asm, Enemy/en_red]
      - [0x060ab0, asm, Enemy/en_scu]
      - [0x065700, asm, Enemy/en_tyu]
      - [0x068ed0, asm, Fog/fog]
      - [0x06cfa0, asm, Fog/fogdata]
      - [0x06ee60, asm, Fog/sh2gfw_fogtest_main]
      - [0x06f070, asm, SH2_common/sh_vu0]
      - [0x06fc40, asm, Fog/spack]
      - [0x071920, c,   Font/dic]
      - [0x072de0, asm, GFW/gfw_test/camera]
      - [0x073030, asm, GFW/gfw_test/kari_probe_draw]
      - [0x0745e0, asm, GFW/gfw_test/sh2_dmachain_regist]
      - [0x0748b0, asm, GFW/gfw_test/sh2gfw_shcamtest]
      - [0x074ac0, asm, GFW/gfw_test/sh2gfw_util]
      - [0x0758d0, asm, GFW/sh2_get_drawenv]
      - [0x075eb0, asm, GFW/sh2_set_drawenv]
      - [0x076690, asm, GFW/sh2_shadow_filters]
      - [0x0771c0, asm, GFW/sh2_shadow_main]
      - [0x0773e0, asm, GFW/sh2gfw_2d_filters]
      - [0x07bde0, asm, GFW/sh2gfw_GSCTL_man]
      - [0x07bfa0, asm, GFW/sh2gfw_Init_ModelDrawData]
      - [0x07d9a0, asm, GFW/sh2gfw_LightSet]
      - [0x07eb80, asm, GFW/sh2gfw_Texpacket]
      - [0x07ff40, asm, GFW/sh2gfw_Vertexpacket]
      - [0x080830, asm, GFW/sh2gfw_alltexman]
      - [0x080840, asm, GFW/sh2gfw_packetVU]
      - [0x080df0, asm, GFW/sh2gfw_parse_and_packet]
      - [0x082650, asm, GFW/sh2gfw_read_process]
      - [0x082f60, asm, GFW/sh2gfw_viewclip]
      - [0x0848f0, asm, Heap/sh2_ch_malloc]
      - [0x084b50, c,   Heap/utilheap]
      - [0x084e10, asm, Lens/kari_lf_draw]
      - [0x087720, asm, Lens/lens_flare]
      - [0x087a90, asm, GFW/sh2_get_drawenv]
      - [0x087f00, asm, Chacter/fi_calc]
      - [0x0883c0, asm, Lens/lens_th_draw]
      - [0x088a60, asm, Multi_thr/dma/dma1cmd]
      - [0x088c70, asm, Multi_thr/dma/dma1serv]
      - [0x088e00, asm, Multi_thr/dma/dma1tscmd]
      - [0x088ed0, asm, Multi_thr/dma/dma2cmd]
      - [0x089090, asm, Multi_thr/dma/dma2serv]
      - [0x089270, asm, Multi_thr/dma/dma2tscmd]
      - [0x0893f0, asm, Multi_thr/dma/sh_dma1]
      - [0x0897d0, asm, Multi_thr/dma/sh_dma2]
      - [0x089bc0, asm, Multi_thr/dma/texslot]
      - [0x089e30, asm, Multi_thr/util/cmd_serv]
      - [0x08b280, asm, Multi_thr/util/utilexcl]
      - [0x08b390, asm, Multi_thr/util/utilstr]
      - [0x08bbc0, asm, shPad/lib_sh_pad]
      - [0x08c760, asm, sh2shd/sh2shd_char_jms]
      - [0x08f6c0, asm, shGs/sh2gfw_GS_NewLoopEnv]
      - [0x08fcd0, asm, shGs/sh2gfw_GsInit]
      - [0x0913c0, asm, sound/sd0712/ee/sd_call]
      - [0x092560, asm, sound/sh_sound]
      - [0x0955b0, asm, taskman/shtskman]
      - [0x095930, asm, view/vb_main]
      - [0x0960e0, asm, view/vc_main]
      - [0x09e490, asm, view/vc_util]
      - [0x09ed40, asm, view/vw_calc]
      - [0x09f720, asm, view/vw_main]
      - [0x09f9f0, c,   main]
      - [0x09fe30, asm, sh2gfw_all_sysinit]
      - [0x0a0280, asm, sh2gfw_drawloop_main]
      - [0x0a1020, asm, sh2shd/sh2shd_outdoor]
      - [0x0a2350, asm, sh2shd/sh2shd_shadow_model]
      - [0x0a66c0, asm, sh2shd/sh2shd_shadow_vu1_packet]
      - [0x0a6d00, asm, sh2shd/sh2shd_stencil_shadow_main]
      - [0x0a6ed0, asm, sh2shd/sh2shd_structs]
      - [0x0a6ef0, asm, view/vc_calc]
      - [0x0a7580, asm, Event/event]
      - [0x0ac650, asm, Event/event_sub]
      - [0x0adf60, asm, Event/item]
      - [0x0aea60, asm, Event/picture]
      - [0x0af7a0, asm, Event/stg_name]
      - [0x0b1450, asm, Event/vu0_func]
      - [0x0b1480, asm, Event/demoview]
      - [0x0b3e30, c,   Font/font]
      - [0x0bab70, asm, Multi_thr/filesys/filecmd]
      - [0x0bc760, asm, Multi_thr/filesys/filepath]
      - [0x0bcd30, asm, Multi_thr/filesys/fileserv]
      - [0x0bd2c0, asm, Multi_thr/filesys/iopload]
      - [0x0bd3a0, asm, Multi_thr/filesys/sh_cdvd]
      - [0x0be810, asm, Multi_thr/filesys/sh_chk_syscnf]
      - [0x0bea60, asm, Multi_thr/intc/syncv]
      - [0x0bed80, asm, Multi_thr/intc/th_vbe]
      - [0x0bef20, asm, Multi_thr/pad/keydata]
      - [0x0bfc40, asm, Multi_thr/pad/th_pad]
      - [0x0bff00, asm, Multi_thr/sys/init_mt_sys]
      - [0x0c0820, asm, Multi_thr/boot/bootopt]
      - [0x0c0a70, asm, Multi_thr/boot/bootoptitem]
      - [0x0c1200, asm, Event/title]
      - [0x0c5a20, asm, SH2_common/pad]
      - [0x0c6500, asm, DBG/dbfntprint]
      - [0x0c6b90, c,   Chacter/sh2_character_manage]
      - [0x0c71a0, asm, DBG/verbose]
      - [0x0c7290, asm, Event/chizu]
      - [0x0cb1f0, asm, Event/chara_admin]
      - [0x0cd7b0, asm, Fog/spkTexMan]
      - [0x0cda60, asm, Font/fj_man]
      - [0x0cdf30, asm, DBG/dbkernel]
      - [0x0ce0b0, asm, DBG/dbflag]
      - [0x0ce240, asm, Item/otn_itemmain]
      - [0x0db910, asm, FilesList/fileslist_bg]
      - [0x0db9a0, asm, Enemy/en_fly]
      - [0x0dc570, asm, Multi_thr/kernel/wrap_printf]
      - [0x0dc5b0, asm, sdk]
      - [0x109850, asm, Item/item_tgs_tmp]
      - [0x109cc0, asm, Multi_thr/intc/th_vbs]
      - [0x109e90, asm, DBG/shDBG_fontHandle]
      - [0x10a2b0, asm, Chacter/m3_edb]
      - [0x10a960, asm, sh2_init]
      - [0x10af50, asm, gamemain]
      - [0x10c460, asm, connect]
      - [0x10c950, asm, logo]
      - [0x10e1c0, asm, Chacter/m3_nse]
      - [0x10e600, asm, Effect/screen_effect]
      - [0x10e950, asm, GFW/sh2gfw_SemiTrans_FrameWork]
      - [0x10f000, asm, Fog/spack]
      - [0x10f800, c,   jump_menu]
      - [0x110cf0, asm, DBG/dbflow]
      - [0x110fc0, asm, Item/otn_option]
      - [0x11c4c0, asm, Chacter/m3_play_common]
      - [0x120870, asm, SH2_common/sh2dt]
      - [0x120990, asm, Chacter/m3_maria]
      - [0x120e00, asm, Chacter/m3_tyu]
      - [0x121210, asm, Chacter/m3_bos]
      - [0x121750, asm, Chacter/m3_oni]
      - [0x121c30, asm, sound/snd_select]
      - [0x122340, asm, Chacter/m3_nik]
      - [0x122560, asm, Multi_thr/loadinit/loadinit]
      - [0x122690, asm, DBG/dbswitch]
      - [0x122b20, asm, Effect/ef_cartridge]
      - [0x1242d0, asm, Chacter/m3_maria_sub]
      - [0x128a00, asm, Event/stg_overlay]
      - [0x129200, asm, Enemy/en_oni]
      - [0x12c730, asm, Multi_thr/scf/ps2_scf]
      - [0x12ca20, asm, DBG/dbfreeze]
      - [0x12cbb0, asm, Effect/ef_rain]
      - [0x12d7e0, asm, SH2_common/data_load]
      - [0x12de00, asm, Effect/ef_smoke]
      - [0x12ed10, asm, Effect/ef_flame]
      - [0x130be0, asm, Event/memo]
      - [0x132c90, asm, Effect/ef_sparks]
      - [0x133550, c,   DS_Pad/ds_sequencer]
      - [0x134ec0, asm, DS_Pad/dss_wrapper]
      - [0x135050, asm, DBG/dbsw_all]
      - [0x1354a0, asm, DBG/dbsw_sys]
      - [0x136350, asm, Event/chara_data_load]
      - [0x1395d0, asm, Chacter/m3_arm]
      - [0x139a00, asm, Chacter/m3_mary]
      - [0x139ca0, asm, Chacter/m3_mxx]
      - [0x139db0, asm, Enemy/en_arm]
      - [0x13b3b0, asm, MC/mc]
      - [0x143370, asm, MC/mc_menu]
      - [0x1480d0, asm, MC/savedata]
      - [0x148790, asm, Event/stage/stg_tgs_trial]
      - [0x14c2b0, asm, Chacter/m3_rpjames]
      - [0x14ca60, asm, Chacter/m3_rwep]
      - [0x151530, asm, GFW/sh2_DrawEnvData]
      - [0x1521e0, asm, LoadBg/loadbg_camdata]
      - [0x1522f0, asm, LoadBg/loadbg_common]
      - [0x152850, asm, DBG/dbsw_map]
      - [0x152c10, asm, Chacter/chara_saveinfo]
      - [0x152e70, asm, view/vc_newest]
      - [0x153490, asm, Multi_thr/scf/sh2_scf]
      - [0x153950, asm, DBG/dbalocate]
      - [0x1539b0, asm, Chacter/bg_chara]
      - [0x154200, asm, Effect2/hh_class_blood_00]
      - [0x1549e0, asm, Effect2/hh_class_blood_01]
      - [0x1551f0, asm, Effect2/hh_class_blood_02]
      - [0x155b30, asm, Effect2/hh_class_blood_03]
      - [0x1562e0, asm, Effect2/hh_class_blood_footmark_00]
      - [0x156750, asm, Effect2/hh_class_blood_pool_phenomenon_00]
      - [0x156a70, asm, Effect2/hh_class_blood_splash_phenomenon_00]
      - [0x157550, asm, Effect2/hh_class_blood_splash_phenomenon_01]
      - [0x157b00, asm, Effect2/hh_class_blood_stick_00]
      - [0x157f40, asm, Effect2/hh_class_dust_00]
      - [0x158790, asm, Effect2/hh_class_glass_break_phenomenon_00]
      - [0x159110, asm, Effect2/hh_class_glass_piece_00]
      - [0x159ce0, asm, Effect2/hh_class_manager]
      - [0x15ad80, asm, Effect2/hh_class_object_execute]
      - [0x15b560, asm, Effect2/hh_class_plural_phenomenon_00]
      - [0x15b930, asm, Effect2/hh_class_raise_dust_phenomenon_00]
      - [0x15bee0, asm, Effect2/hh_class_water_00]
      - [0x15ce40, asm, Effect2/hh_class_water_01]
      - [0x15e140, asm, Effect2/hh_class_water_02]
      - [0x15f610, asm, Effect2/hh_class_water_10]
      - [0x160640, asm, Effect2/hh_class_water_11]
      - [0x161b00, asm, Effect2/hh_class_water_12]
      - [0x162ff0, asm, Effect2/hh_class_water_13]
      - [0x164240, asm, Effect2/hh_class_water_14]
      - [0x165530, asm, Effect2/hh_class_water_15]
      - [0x166b00, asm, Effect2/hh_class_water_20]
      - [0x167360, asm, Effect2/hh_class_water_30]
      - [0x168720, asm, Effect2/hh_class_water_common]
      - [0x1691d0, asm, Effect2/hh_class_water_splash_phenomenon_00]
      - [0x169790, asm, Effect2/hh_class_wrapper]
      - [0x16a310, asm, Effect2/hh_dbg_wrapper]
      - [0x16a4b0, asm, Effect2/hh_effect_object_def]
      - [0x16ab10, asm, Effect2/hh_effect_object_texture]
      - [0x16b9c0, asm, Effect2/hh_math_wrapper]
      - [0x16bae0, asm, Effect2/hh_packet]
      - [0x16c1c0, asm, Multi_thr/filesys/fcread]
      - [0x16c4c0, asm, Chacter/m3_boat_jms]
      - [0x16c780, asm, Chacter/m3_boat]
      - [0x16f630, asm, Chacter/lake_wave]
      - [0x16fbf0, asm, Chacter/m3_inu]
      - [0x16fe80, asm, view/vc_play]
      - [0x170010, asm, LoadBg/loadbg_2x2]
      - [0x1711d0, asm, LoadBg/loadbg_all]
      - [0x172180, asm, LoadBg/loadbg_cam]
      - [0x1726c0, asm, LoadBg/loadbg_cld]
      - [0x172ab0, asm, LoadBg/loadbg_kg2]
      - [0x172eb0, asm, LoadBg/loadbg_map]
      - [0x1736f0, asm, LoadBg/loadbg_mem]
      - [0x1753a0, asm, Fog/fog_blow]
      - [0x175fa0, asm, Chacter/chara_bound]
      - [0x176030, asm, Chacter/charaboundtbl]
      - [0x176040, asm, Effect2/hh_class_water_03]
      - [0x1773a0, asm, Effect2/hh_class_water_04]
      - [0x1787c0, asm, Effect2/hh_class_water_06]
      - [0x179c50, asm, Effect2/hh_class_water_07]
      - [0x17b070, asm, Effect2/hh_class_water_08]
      - [0x17c4a0, asm, Effect2/hh_class_water_09]
      - [0x17d7b0, asm, Enemy/en_insect]
      - [0x17ea10, asm, sh2shd/sh2shd_shadow_env]
      - [0x181300, asm, Effect2/hh_class_fire_phenomenon_00]
      - [0x1816f0, asm, Effect2/hh_class_flame_00]
      - [0x182150, asm, Effect2/hh_class_flame_01]
      - [0x182bf0, asm, Effect2/hh_class_smoke_00]
      - [0x1835c0, asm, Effect2/hh_class_water_pool_00]
      - [0x183e40, asm, Chacter/m3_play_event]
      - [0x184830, asm, Chacter/m3_play_efect]
      - [0x1869a0, asm, LoadBg/loadbg_1x1]
      - [0x186ae0, asm, Effect2/hh_class_flame_02]
      - [0x187590, asm, Effect2/hh_class_plural_phenomenon_01]
      - [0x187b80, asm, movie/movie_main]
      - [0x188380, asm, movie/pss_audiodec]
      - [0x188dd0, asm, movie/pss_common]
      - [0x188ee0, asm, movie/pss_cscvu1]
      - [0x18a220, asm, movie/pss_disp]
      - [0x18b210, asm, movie/pss_main]
      - [0x18c3d0, asm, movie/pss_read]
      - [0x18c790, asm, movie/pss_readbuf]
      - [0x18c9f0, asm, movie/pss_strfile]
      - [0x18cb80, c,   movie/pss_vibuf]
      - [0x18dc60, asm, movie/pss_videodec]
      - [0x18e590, asm, movie/pss_vobuf]
      - [0x18e7b0, asm, Chacter_Draw/sh2_JmsSpot_Man]
      - [0x18f7c0, asm, LoadBg/loadbg_event]
      - [0x18fe00, asm, LoadBg/loadbg_chara]
      - [0x1909d0, asm, Chacter/player_result]
      - [0x1913a0, asm, sound/sh_sd_call]
      - [0x191c00, asm, Chacter/m3_ty23]
      - [0x191d20, asm, Effect2/hh_class_blood_04]
      - [0x1924f0, asm, Effect2/hh_class_blood_pool_phenomenon_01]
      - [0x192aa0, asm, Effect2/hh_memory_manage]
      - [0x192f50, asm, SH2_common/mem_share]
      - [0x1937c0, asm, Effect2/hh_class_flame_03]
      - [0x194300, asm, SH2_common/result]
      - [0x1951b0, asm, view/vc_prio]
      - [0x195480, asm, Effect2/hh_class_blood_05]
      - [0x195cc0, asm, Effect2/hh_class_blood_splash_phenomenon_02]
      - [0x196800, asm, Effect2/hh_class_water_80]
      - [0x197870, asm, Effect2/hh_class_water_90]
      - [0x1988b0, asm, Effect2/hh_class_boatmask]
      - [0x199090, asm, pause]
      - [0x1996a0, asm, now_loading]
      - [0x1999a8, data, data]
      - [0x28cf40, .rodata, Chacter/m3_sc]
      - [0x28cf60,  rodata, rodata_0]
      - [0x28e0b0, .rodata, Chacter_Draw/model3_vu1_n]
      - [0x28e2c0, .rodata, rodata_1]
      - [0x291ac0, .rodata, Font/font]
      - [0x291c00,  rodata, rodata_2]
      - { vram: 0x3c7d80, type: bss, name: bss }
  - [0x2c8480]
